name: Convert DOCX to JSON and Push to S3

on:
  push:
    branches:
      - converting_docx_to_json

jobs:
  convert-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install python-docx
          pip install docx simplify-docx

      - name: Convert DOCX to JSON
        run: |
          python convert_docx_to_json.py
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JSON to S3
        run: |
          aws s3 cp . s3://s3-json-bucket --recursive --exclude "*" --include "*.json" --exclude "*.md"
